### PR TITLE
Scrs 8208

### PR DESCRIPTION
**Pull request by henrilay**

### CODE REVIEW

**Comment by CEPoole** [comment]
Master is currently blocked by **SCRS-8424** until deployments issues are resolved

**Comment by lesjoneshmrc** [comment]
Rebased onto master (commit tip changed from d54ac161e to 797c3e3)

**Comment by lesjoneshmrc** [comment]
Now blocked by SCRS-7686; awaiting QA & prod deployment.

**Comment by lesjoneshmrc** [comment]
@henrilay FYI I've added a connector test. Can you also look at these comments (I've rebased so you'll need to reset after a force fetch) :
- CorporationTaxRegistrationSpec contains a println; please remove
- MongoValidation::emailBooleanRead are you sure this is right, I think this should be the same (i.e. as it was)?
- As above for MongoValidation::lastSignedInDateTimeRead

**Comment by lesjoneshmrc** [comment]
Ready to merge - waiting for the pipeline to prod to be clear.

**Pull request merged**
